# Generated by Django 4.2.30 on 2026-04-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_strikes', models.IntegerField(default=0, help_text='Successful attacks/strikes')),
                ('home_blocks', models.IntegerField(default=0, help_text='Successful blocks')),
                ('home_service_aces', models.IntegerField(default=0, help_text='Service aces (unreturnable serves)')),
                ('home_errors', models.IntegerField(default=0, help_text='Unforced errors')),
                ('away_strikes', models.IntegerField(default=0, help_text='Successful attacks/strikes')),
                ('away_blocks', models.IntegerField(default=0, help_text='Successful blocks')),
                ('away_service_aces', models.IntegerField(default=0, help_text='Service aces (unreturnable serves)')),
                ('away_errors', models.IntegerField(default=0, help_text='Unforced errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='scheduling.match')),
            ],
        ),
    ]
